import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/theme/app_theme.dart';
import 'routes/app_routes.dart';
import '../screens/services/auth_service.dart';
import '../screens/services/peminjaman_service.dart';
import 'screens/splash/splash_page.dart';

Future<void> main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  // Keep the native splash (the one generated by flutter_native_splash,
  // shown before Flutter draws its first frame) on screen through all
  // the async setup below, instead of letting it disappear the instant
  // the first frame renders. Without this, there'd be a flash of a
  // blank/default screen between the native splash disappearing and
  // SplashPage actually finishing its own setup — removing it manually
  // right before runApp() means the native splash hands off directly
  // to SplashPage with no gap.
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  // ── Get these two values from your Supabase project:
  // Dashboard → Project Settings → API → Project URL / anon public key
  await Supabase.initialize(
    url: 'https://axiulqpwrzbzihphfwwm.supabase.co',
    anonKey:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aXVscXB3cnpiemlocGhmd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2Mzk1NTcsImV4cCI6MjA5OTIxNTU1N30.Ke20mXol554sglYHvwfGfCOjyJcTxsQ3YG6-D3oYMOs',
  );

  // DEV ONLY — forces the onboarding slides to show on every hot restart,
  // regardless of a restored session or the persisted onboarding_seen
  // flag. Only active in debug builds (kDebugMode), so it never runs in
  // a release/profile build. Set this to false to go back to normal
  // behavior (skip onboarding when a session is restored).
  const forceOnboardingInDebug = true;

  // Previously this just checked Supabase's raw currentSession directly
  // and never called AuthService.tryRestoreSession() at all — so every
  // bit of offline-fallback logic built into that method (cached profile
  // via SharedPreferences, isOfflineSession, etc.) never actually ran on
  // startup; AuthService.currentUser stayed null even with a valid
  // restored session. tryRestoreSession() does the same currentSession
  // check internally, plus the profile-load-with-offline-fallback on
  // top, so this is a strict upgrade — same behavior when online, but
  // actually usable when offline.
  final restored = await AuthService.tryRestoreSession();
  if (restored) {
    // This used to have no try/catch: PeminjamanService.refresh() always
    // hits the network, and an uncaught exception here — guaranteed
    // when offline — would stop main() before runApp() ever ran. The
    // whole app would just hang on the native splash screen forever
    // with no error shown, indistinguishable from a crash. A failed
    // refresh here isn't fatal: HomePage/HistoryPage will just show
    // whatever's already in PeminjamanService's cache (empty on a
    // genuinely fresh install, but populated on any subsequent offline
    // open) instead of the latest data.
    try {
      await PeminjamanService.refresh();
    } catch (_) {
      // Non-fatal — see comment above.
    }
  }

  // Onboarding only ever shows once, on a fresh install / before first
  // login — never again after that, even after logout.
  final prefs = await SharedPreferences.getInstance();
  final seenOnboarding = prefs.getBool('onboarding_seen') ?? false;

  // Same decision as before — just renamed, since it's no longer the
  // literal first route. It's now where SplashPage sends the user once
  // its animation finishes (see MyApp below / SplashPage.nextRoute).
  final String nextRoute;
  if (kDebugMode && forceOnboardingInDebug) {
    nextRoute = AppRoutes.onboarding;
  } else if (restored) {
    nextRoute = AppRoutes.home;
  } else if (!seenOnboarding) {
    nextRoute = AppRoutes.onboarding;
  } else {
    nextRoute = AppRoutes.login;
  }

  // Native splash removal now happens inside SplashPage itself (see
  // splash_page.dart's initState), *after* its first frame actually
  // renders — not here. Removing it here, right before runApp(), doesn't
  // wait for that first frame: runApp() only schedules the build, it
  // doesn't block until pixels are on screen, so the native splash could
  // disappear a beat before SplashPage was actually ready to be seen —
  // visible as the two splashes flashing/overlapping briefly instead of
  // a clean handoff.
  runApp(MyApp(nextRoute: nextRoute));
}

class MyApp extends StatelessWidget {
  final String nextRoute;
  const MyApp({super.key, required this.nextRoute});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Aplikasi Arsip',
      theme: AppTheme.lightTheme,
      // Every cold start now opens on SplashPage first, regardless of
      // nextRoute — it plays its intro animation, then does
      // pushReplacementNamed(nextRoute) itself once that finishes. This
      // is a plain widget built directly with `home:`, not a named
      // route, precisely so it's NOT part of the route table and can't
      // be navigated back to with the back button once it's been
      // replaced.
      //
      // The NOT-`initialRoute:` reasoning from before still applies to
      // nextRoute itself, just one level down — see SplashPage's
      // Navigator.pushReplacementNamed call, which goes through
      // AppRoutes.onGenerateRoute like any other named navigation, so
      // there's still no phantom "/" route hiding underneath it.
      home: SplashPage(nextRoute: nextRoute),
      onGenerateRoute: AppRoutes.onGenerateRoute,
    );
  }
}
